2020-12-20 03:58:25,202     ERROR logging_test <module>: error message
2020-12-20 03:58:25,202     ERROR logging_test <module>: division by zero occurred
Traceback (most recent call last):
  File "logging_test.py", line 16, in <module>
    42/0
ZeroDivisionError: division by zero
2020-12-20 03:58:25,202  CRITICAL logging_test <module>: critical error message
